spring:
  mail:
    host: smtp.163.com
    port: 465
    protocol: smtp
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            required: true
