server:
  port: 8090

spring:
  application:
    name: work-push
  profiles:
    active: dev
  # redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000 # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 最大连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 5000 # 最大等待时间