server:
  port: 8090

spring:
  application:
    name: work-push
  profiles:
    active: dev
  # redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000 # 连接超时时间
      lettuce:
        pool:
          max-active: 8 # 最大连接数
          max-idle: 8 # 最大空闲连接数
          min-idle: 0 # 最小空闲连接数
          max-wait: 5000 # 最大等待时间
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: ly20030321
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # 连接池最大连接数